deckservice:
  image: slidewiki/deckservice
  restart: on-failure:5
  expose:
    - "80"
  external_links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=deckservice.experimental.slidewiki.org
    - SERVICE_URL_FILE=fileservice.experimental.slidewiki.org
    - SERVICE_URL_IMAGE=imageservice.experimental.slidewiki.org
    - JWT_SERIAL=69aac7f95a9152cd4ae7667c80557c284e413d748cca4c5715b3f02020a5ae1b
